name: workflow test
on: push
jobs:
  id: flask test
  name: GitHub Actions Demo
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: Run
      run: python -m pip install â€“upgrade pip
      | pip3 install -r requirements.txt
      | python3 server.py > log.txt 2>&1 &

